In [2]:
import pandas as pd 

df = pd.read_csv(r'data/Euronext_Equities_2025-08-19.csv', sep = ';')

In [3]:
df['Market'].dropna().unique()

array(['Oslo Børs', 'Euronext Growth Paris', 'EuroTLX',
       'Euronext Global Equity Market', 'Trading After Hours',
       'Euronext Growth Milan', 'Euronext Expand Oslo', 'Euronext Paris',
       'Euronext Milan', 'Euronext Amsterdam', 'Euronext Growth Oslo',
       'Euronext Brussels', 'Euronext Expert Market',
       'Euronext Brussels, Paris', 'Euronext Access Paris',
       'Euronext Access Brussels', 'Euronext Brussels, Amsterdam',
       'Euronext Amsterdam, Brussels', 'Euronext Dublin',
       'Euronext Paris, Amsterdam', 'Euronext Lisbon',
       'Euronext Amsterdam, Brussels, Paris', 'Euronext Growth Dublin',
       'Euronext Amsterdam, Paris', 'Euronext Access Lisbon',
       'Euronext Growth Brussels', 'Euronext Paris, Brussels',
       'Euronext Paris, Amsterdam, Brussels',
       'Euronext Growth Brussels, Paris',
       'Euronext Growth Paris, Brussels',
       'Euronext Brussels, Amsterdam, Paris', 'Euronext Growth Lisbon'],
      dtype=object)

In [16]:
import yfinance as yf
data = yf.Ticker('DNB.OL')

In [17]:
data.info

{'address1': 'Dronning Eufemias gate 30',
 'address2': 'Bjørvika',
 'city': 'Oslo',
 'zip': '0191',
 'country': 'Norway',
 'phone': '47 91 50 48 00',
 'website': 'https://www.dnb.no',
 'industry': 'Banks - Regional',
 'industryKey': 'banks-regional',
 'industryDisp': 'Banks - Regional',
 'sector': 'Financial Services',
 'sectorKey': 'financial-services',
 'sectorDisp': 'Financial Services',
 'longBusinessSummary': 'DNB Bank ASA provides financial services to individuals and businesses in Norway and internationally. The company offers savings, current, currency, client, tax withholding, and pension accounts; fixed rate and security deposits; home and cabin mortgages, construction and fixed-rate loans, car and consumer loans, business loans, and refinancing; home equity credit lines; car, house, home contents, travel, personal, and non-life insurance products; payment services; and online and mobile banking services, as well as cards. It also provides overdraft facilities; leasing services; factoring, supply chain, and receivable purchase financing services; bank guarantees; secure trading, documentary collection, and letter of credit services; investment banking services, such as mergers and acquisitions, equity and debt capital market, loans, bonds, convertible bonds, direct lending, and other private placements; and private financing and commodities, as well as equity trading, foreign exchange, research, share and stock market, securities, and risk advisory services. In addition, the company offers treasury management, working capital, trade finance, equipment financing, real estate broking, and corporate finance services. DNB Bank ASA was founded in 1822 and is headquartered in Oslo, Norway.',
 'fullTimeEmployees': 11045,
 'companyOfficers': [{'maxAge': 1,
   'name': 'Ms. Kjerstin Rasmussen Braathen',
   'age': 54,
   'title': 'Group Chief Executive Officer',
   'yearBorn': 1970,
   'fiscalYear': 2024,
   'totalPay': 14877000,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Ms. Ida  Lerner',
   'age': 49,
   'title': 'Group Chief Financial Officer',
   'yearBorn': 1975,
   'fiscalYear': 2024,
   'totalPay': 7957000,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Ms. Maria Ervik Loevold',
   'age': 45,
   'title': 'Group EVP of the Retail Market & Personal Banking and COO',
   'yearBorn': 1979,
   'fiscalYear': 2024,
   'totalPay': 5720000,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Ms. Elin  Sandnes',
   'age': 36,
   'title': 'Group Executive Vice President of Technology & Services',
   'yearBorn': 1988,
   'fiscalYear': 2024,
   'totalPay': 4470840,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Fredrik  Berger',
   'age': 43,
   'title': 'Group Executive VP of Group Compliance & Group Chief Compliance Officer',
   'yearBorn': 1981,
   'fiscalYear': 2024,
   'totalPay': 5046000,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Even Graff Westerveld',
   'age': 44,
   'title': 'Group Executive Vice President of People & Communication',
   'yearBorn': 1980,
   'fiscalYear': 2024,
   'totalPay': 4535000,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Harald  Serck-Hanssen',
   'age': 59,
   'title': 'Group Executive Vice President of Large Corporates & International',
   'yearBorn': 1965,
   'fiscalYear': 2024,
   'totalPay': 8924000,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Rasmus Aage T. Figenschou',
   'age': 45,
   'title': 'Group EVP of Corporate Banking Norway & EVP of Corporate Market',
   'yearBorn': 1979,
   'fiscalYear': 2024,
   'totalPay': 5417814,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Hakon Elvekrok Hansen',
   'age': 58,
   'title': 'Group Executive Vice President of Wealth Management',
   'yearBorn': 1966,
   'fiscalYear': 2024,
   'totalPay': 5694000,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Morten  Opstad',
   'age': 43,
   'title': 'Group Executive Vice President of Markets',
   'yearBorn': 1981,
   'fiscalYear': 2024,
   'totalPay': 12139000,
   'exercisedValue': 0,
   'unexercisedValue': 0}],
 'auditRisk': 3,
 'boardRisk': 2,
 'compensationRisk': 1,
 'shareHolderRightsRisk': 4,
 'overallRisk': 1,
 'governanceEpochDate': 1759276800,
 'compensationAsOfEpochDate': 1735603200,
 'executiveTeam': [],
 'maxAge': 86400,
 'priceHint': 2,
 'previousClose': 269.7,
 'open': 270.0,
 'dayLow': 270.0,
 'dayHigh': 273.2,
 'regularMarketPreviousClose': 269.7,
 'regularMarketOpen': 270.0,
 'regularMarketDayLow': 270.0,
 'regularMarketDayHigh': 273.2,
 'dividendRate': 16.75,
 'dividendYield': 6.21,
 'exDividendDate': 1745971200,
 'payoutRatio': 0.561,
 'fiveYearAvgDividendYield': 4.3,
 'beta': 0.425,
 'trailingPE': 9.075686,
 'forwardPE': 10.940654,
 'volume': 1315219,
 'regularMarketVolume': 1315219,
 'averageVolume': 1362749,
 'averageVolume10days': 1158818,
 'averageDailyVolume10Day': 1158818,
 'bid': 271.7,
 'ask': 271.9,
 'bidSize': 3277,
 'askSize': 2464,
 'marketCap': 397788119040,
 'fiftyTwoWeekLow': 221.5,
 'fiftyTwoWeekHigh': 284.5,
 'allTimeHigh': 284.5,
 'allTimeLow': 14.148703,
 'priceToSalesTrailing12Months': 4.542101,
 'fiftyDayAverage': 268.64,
 'twoHundredDayAverage': 263.1935,
 'trailingAnnualDividendRate': 16.75,
 'trailingAnnualDividendYield': 0.06210604,
 'currency': 'NOK',
 'tradeable': False,
 'enterpriseValue': 1121557020672,
 'profitMargins': 0.52639,
 'floatShares': 1478845766,
 'sharesOutstanding': 1467852793,
 'heldPercentInsiders': 0.45099998,
 'heldPercentInstitutions': 0.42141,
 'impliedSharesOutstanding': 1487990188,
 'bookValue': 171.559,
 'priceToBook': 1.5796314,
 'lastFiscalYearEnd': 1735603200,
 'nextFiscalYearEnd': 1767139200,
 'mostRecentQuarter': 1751241600,
 'earningsQuarterlyGrowth': -0.029,
 'netIncomeToCommon': 44301000704,
 'trailingEps': 29.86,
 'forwardEps': 24.77,
 'enterpriseToRevenue': 12.806,
 '52WeekChange': 0.20509386,
 'SandP52WeekChange': 0.13837254,
 'lastDividendValue': 16.75,
 'lastDividendDate': 1745971200,
 'quoteType': 'EQUITY',
 'currentPrice': 271.0,
 'targetHighPrice': 326.0,
 'targetLowPrice': 240.0,
 'targetMeanPrice': 277.4,
 'targetMedianPrice': 280.0,
 'recommendationMean': 3.07143,
 'recommendationKey': 'hold',
 'numberOfAnalystOpinions': 15,
 'totalCash': 812684017664,
 'totalCashPerShare': 549.122,
 'totalDebt': 1534422024192,
 'totalRevenue': 87578001408,
 'revenuePerShare': 59.084,
 'returnOnAssets': 0.01228,
 'returnOnEquity': 0.16896999,
 'grossProfits': 87578001408,
 'operatingCashflow': -44983001088,
 'earningsGrowth': -0.006,
 'revenueGrowth': 0.039,
 'grossMargins': 0.0,
 'ebitdaMargins': 0.0,
 'operatingMargins': 0.60247004,
 'financialCurrency': 'NOK',
 'symbol': 'DNB.OL',
 'language': 'en-US',
 'region': 'US',
 'typeDisp': 'Equity',
 'quoteSourceName': 'Delayed Quote',
 'triggerable': False,
 'customPriceAlertConfidence': 'LOW',
 'exchange': 'OSL',
 'messageBoardId': 'finmb_9778651',
 'exchangeTimezoneName': 'Europe/Oslo',
 'exchangeTimezoneShortName': 'CEST',
 'gmtOffSetMilliseconds': 7200000,
 'market': 'no_market',
 'esgPopulated': False,
 'corporateActions': [],
 'regularMarketTime': 1760970549,
 'marketState': 'PREPRE',
 'shortName': 'DNB BANK ASA',
 'longName': 'DNB Bank ASA',
 'regularMarketChangePercent': 0.4820125,
 'regularMarketPrice': 271.0,
 'fiftyTwoWeekLowChangePercent': 0.22347629,
 'fiftyTwoWeekRange': '221.5 - 284.5',
 'fiftyTwoWeekHighChange': -13.5,
 'fiftyTwoWeekHighChangePercent': -0.04745167,
 'fiftyTwoWeekChangePercent': 20.509386,
 'earningsTimestamp': 1761142800,
 'earningsTimestampStart': 1761142800,
 'earningsTimestampEnd': 1761142800,
 'earningsCallTimestampStart': 1761132600,
 'earningsCallTimestampEnd': 1761132600,
 'isEarningsDateEstimate': False,
 'epsTrailingTwelveMonths': 29.86,
 'epsForward': 24.77,
 'epsCurrentYear': 27.73783,
 'priceEpsCurrentYear': 9.770051,
 'fiftyDayAverageChange': 2.3599854,
 'fiftyDayAverageChangePercent': 0.008784936,
 'twoHundredDayAverageChange': 7.806488,
 'twoHundredDayAverageChangePercent': 0.02966064,
 'sourceInterval': 15,
 'exchangeDataDelayedBy': 15,
 'averageAnalystRating': '3.1 - Hold',
 'cryptoTradeable': False,
 'hasPrePostMarketData': False,
 'firstTradeDateMilliseconds': 946886400000,
 'regularMarketChange': 1.2999878,
 'regularMarketDayRange': '270.0 - 273.2',
 'fullExchangeName': 'Oslo',
 'averageDailyVolume3Month': 1362749,
 'fiftyTwoWeekLowChange': 49.5,
 'trailingPegRatio': None}

In [25]:
data.balance_sheet

,2024-12-31,2023-12-31,2022-12-31,2021-12-31,2020-12-31
Treasury Shares Number,9.850699e+06,2.577472e+07,NaN,NaN,NaN
Ordinary Shares Number,1.482680e+09,1.516838e+09,1.550365e+09,1.550365e+09,NaN
Share Issued,1.492530e+09,1.542613e+09,1.550365e+09,1.550365e+09,NaN
Net Debt,8.643060e+11,6.187960e+11,5.260810e+11,4.789770e+11,NaN
Total Debt,1.014425e+12,9.523670e+11,8.386740e+11,7.785000e+11,NaN
...,...,...,...,...,...
Notes Receivable,NaN,1.253000e+09,1.609000e+09,2.518000e+09,2.897000e+09
Other Short Term Investments,NaN,1.945440e+11,1.451720e+11,1.039970e+11,8.948100e+10
Cash And Cash Equivalents,1.479440e+11,3.314080e+11,3.099880e+11,2.967270e+11,NaN
Cash Financial,NaN,NaN,NaN,2.967270e+11,2.835260e+11
Cash Cash Equivalents And Federal Funds Sold,1.479440e+11,3.314080e+11,3.099880e+11,2.967270e+11,NaN

In [26]:
data.balance_sheet.loc['Stockholders Equity'] / (data.balance_sheet.loc['Total Assets'] - data.balance_sheet.loc['Total Liabilities Net Minority Interest'])

2024-12-31    0.999231
2023-12-31    0.999376
2022-12-31    0.999091
2021-12-31    0.998909
2020-12-31         NaN
dtype: float64

In [19]:
data.info['priceToBook']

1.5796314

In [9]:
data.balance_sheet.loc['Stockholders Equity']

2024-12-31    151800000.0
2023-12-31    161000000.0
2022-12-31    155900000.0
2021-12-31    151700000.0
2020-12-31            NaN
Name: Stockholders Equity, dtype: float64

In [33]:
data.income_stmt

,2024-12-31,2023-12-31,2022-12-31,2021-12-31
Tax Effect Of Unusual Items,3.718182e+05,0.000000e+00,0.000000e+00,0.000000e+00
Tax Rate For Calcs,9.091000e-03,5.535100e-02,3.125000e-03,0.000000e+00
Normalized EBITDA,5.240000e+07,4.990000e+07,5.310000e+07,9.200000e+07
Total Unusual Items,4.090000e+07,0.000000e+00,NaN,NaN
Total Unusual Items Excluding Goodwill,4.090000e+07,0.000000e+00,NaN,NaN
Net Income From Continuing Operation Net Minority Interest,7.630000e+07,2.560000e+07,3.190000e+07,7.080000e+07
Reconciled Depreciation,9.500000e+06,1.160000e+07,1.170000e+07,1.170000e+07
Reconciled Cost Of Revenue,2.650000e+07,3.190000e+07,3.140000e+07,3.220000e+07
EBITDA,9.330000e+07,4.990000e+07,5.310000e+07,9.200000e+07
EBIT,8.380000e+07,3.830000e+07,4.140000e+07,8.030000e+07
Net Interest Income,-6.700000e+06,-1.060000e+07,-9.500000e+06,-9.600000e+06
Interest Expense,6.800000e+06,1.120000e+07,9.400000e+06,9.500000e+06
Interest Income,1.000000e+05,6.000000e+05,NaN,NaN
Normalized Income,3.577182e+07,2.560000e+07,3.190000e+07,7.080000e+07
Net Income From Continuing And Discontinued Operation,7.630000e+07,2.560000e+07,3.190000e+07,7.080000e+07
Total Expenses,2.890000e+07,3.200000e+07,3.460000e+07,3.340000e+07
Total Operating Income As Reported,8.370000e+07,3.770000e+07,4.150000e+07,8.040000e+07
Diluted Average Shares,2.287425e+07,2.257493e+07,2.251994e+07,2.255692e+07
Basic Average Shares,2.287091e+07,2.257493e+07,2.222091e+07,2.218460e+07
Diluted EPS,3.340000e+00,1.130000e+00,1.420000e+00,3.140000e+00
Basic EPS,3.340000e+00,1.130000e+00,1.440000e+00,3.190000e+00
Diluted NI Availto Com Stockholders,7.630000e+07,2.560000e+07,3.190000e+07,7.080000e+07
Net Income Common Stockholders,7.630000e+07,2.560000e+07,3.190000e+07,7.080000e+07
Otherunder Preferred Stock Dividend,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
Net Income,7.630000e+07,2.560000e+07,3.190000e+07,7.080000e+07
Net Income Including Noncontrolling Interests,7.630000e+07,2.560000e+07,3.190000e+07,7.080000e+07
Net Income Continuous Operations,7.630000e+07,2.560000e+07,3.190000e+07,7.080000e+07
Tax Provision,7.000000e+05,1.500000e+06,1.000000e+05,0.000000e+00
Pretax Income,7.700000e+07,2.710000e+07,3.200000e+07,7.080000e+07
Special Income Charges,4.090000e+07,0.000000e+00,NaN,NaN
Other Special Charges,-4.090000e+07,NaN,NaN,NaN
Net Non Operating Interest Income Expense,-6.700000e+06,-1.060000e+07,-9.500000e+06,-9.600000e+06
Total Other Finance Cost,-1.000000e+05,-6.000000e+05,1.000000e+05,1.000000e+05
Interest Expense Non Operating,6.800000e+06,1.120000e+07,9.400000e+06,9.500000e+06
Interest Income Non Operating,1.000000e+05,6.000000e+05,NaN,NaN
Operating Income,4.280000e+07,3.770000e+07,4.150000e+07,8.040000e+07
Operating Expense,2.400000e+06,1.000000e+05,3.200000e+06,1.200000e+06
Selling General And Administration,3.900000e+06,3.400000e+06,4.400000e+06,3.300000e+06
General And Administrative Expense,3.900000e+06,3.400000e+06,4.400000e+06,3.300000e+06
Gross Profit,4.520000e+07,3.780000e+07,4.470000e+07,8.160000e+07
Cost Of Revenue,2.650000e+07,3.190000e+07,3.140000e+07,3.220000e+07
Total Revenue,7.170000e+07,6.970000e+07,7.610000e+07,1.138000e+08
Operating Revenue,7.170000e+07,6.970000e+07,7.610000e+07,1.138000e+08

In [46]:
year_av = []
df = data.history(period="10y")
df.index = df.index.tz_localize(None)

for end_date in list(data.incomestmt.loc['Diluted EPS'].index):
    start_date = end_date - pd.DateOffset(years=1)
    average = df.loc[start_date:end_date]['Close'].mean()
    year_av.append(float(average))

In [58]:
data.info['trailingPE']

13.778005

In [52]:
data.incomestmt.loc['Diluted EPS'].dropna()

2024-12-31    3.34
2023-12-31    1.13
2022-12-31    1.42
2021-12-31    3.14
Name: Diluted EPS, dtype: float64

In [48]:
year_av.reverse()

In [49]:
year_av

[96.77774839552622, 101.5785928959903, 99.36319723547217, 143.8657020263672]

In [29]:
hist_data = data.history(period="10y")
hist_data.index = hist_data.index.tz_localize(None)

In [37]:
hist_data

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2019-07-12,79.637098,82.194255,75.801369,75.801369,40831,0.0,0.0
2019-07-15,75.801370,76.696377,73.974831,73.974831,8810,0.0,0.0
2019-07-16,73.974831,73.974831,73.061561,73.974831,21400,0.0,0.0
2019-07-17,73.974831,73.974831,73.527331,73.974831,12966,0.0,0.0
2019-07-18,73.070696,73.070696,70.330888,73.061562,4789,0.0,0.0
...,...,...,...,...,...,...,...
2025-09-29,143.699997,143.800003,135.600006,135.600006,413393,0.0,0.0
2025-09-30,135.399994,136.199997,133.600006,134.300003,255819,0.0,0.0
2025-10-01,134.300003,135.199997,133.100006,134.000000,199156,0.0,0.0
2025-10-02,136.800003,138.699997,135.699997,137.199997,161770,0.0,0.0
2025-10-03,138.600006,138.600006,134.500000,135.300003,128323,0.0,0.0

In [36]:
t1 = data.incomestmt.loc['Diluted EPS'].index[-1] - pd.DateOffset(years=1)
hist_data.loc[t1:data.incomestmt.loc['Diluted EPS'].index[-1]]['Close'].mean()

np.float64(96.7777450046842)

In [32]:
hist_data.index[0]

Timestamp('2019-07-12 00:00:00')

In [31]:
hist_data

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2019-07-12,79.637098,82.194255,75.801369,75.801369,40831,0.0,0.0
2019-07-15,75.801370,76.696377,73.974831,73.974831,8810,0.0,0.0
2019-07-16,73.974831,73.974831,73.061561,73.974831,21400,0.0,0.0
2019-07-17,73.974831,73.974831,73.527331,73.974831,12966,0.0,0.0
2019-07-18,73.070696,73.070696,70.330888,73.061562,4789,0.0,0.0
...,...,...,...,...,...,...,...
2025-09-29,143.699997,143.800003,135.600006,135.600006,413393,0.0,0.0
2025-09-30,135.399994,136.199997,133.600006,134.300003,255819,0.0,0.0
2025-10-01,134.300003,135.199997,133.100006,134.000000,199156,0.0,0.0
2025-10-02,136.800003,138.699997,135.699997,137.199997,161770,0.0,0.0
2025-10-03,138.600006,138.600006,134.500000,135.300003,128323,0.0,0.0